//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime dateStart { get; set; }
        public System.DateTime dateExpier { get; set; }
        public int quantity { get; set; }
        public string status { get; set; }
        public bool active { get; set; }
        public decimal price { get; set; }
    }
}
