//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MucLuc
    {
        public int id { get; set; }
        public string tieu_de { get; set; }
        public Nullable<int> blog_id { get; set; }
        public string content { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
