//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSale.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebBanHangASPEntities3 : DbContext
    {
        public WebBanHangASPEntities3()
            : base("name=WebBanHangASPEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThongSoKyThuat> ThongSoKyThuats { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Shipping> Shippings { get; set; }
        public virtual DbSet<ProductImage> ProductImages { get; set; }
        public virtual DbSet<Transport> Transports { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<Wishlist> Wishlists { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<DanhMucBlog> DanhMucBlogs { get; set; }
        public virtual DbSet<MucLuc> MucLucs { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
    
        public virtual ObjectResult<getListProduct_Result> getListProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getListProduct_Result>("getListProduct");
        }
    
        public virtual ObjectResult<getProductBySlug_Result> getProductBySlug(string slug)
        {
            var slugParameter = slug != null ?
                new ObjectParameter("slug", slug) :
                new ObjectParameter("slug", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getProductBySlug_Result>("getProductBySlug", slugParameter);
        }
    
        public virtual ObjectResult<GetProductDetailsBySlug_Result> GetProductDetailsBySlug(string slug)
        {
            var slugParameter = slug != null ?
                new ObjectParameter("slug", slug) :
                new ObjectParameter("slug", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductDetailsBySlug_Result>("GetProductDetailsBySlug", slugParameter);
        }
    
        public virtual ObjectResult<chiTietSanPham_Result> chiTietSanPham(string slug)
        {
            var slugParameter = slug != null ?
                new ObjectParameter("slug", slug) :
                new ObjectParameter("slug", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<chiTietSanPham_Result>("chiTietSanPham", slugParameter);
        }
    }
}
