//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongSoKyThuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongSoKyThuat()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int specificationId { get; set; }
        public string screenTechnology { get; set; }
        public string screenResolution { get; set; }
        public string screenSize { get; set; }
        public string screenFeatures { get; set; }
        public string refreshRate { get; set; }
        public string rearCamera { get; set; }
        public string rearCameraResolution { get; set; }
        public string videoRecording { get; set; }
        public string flash { get; set; }
        public string rearCameraFeatures { get; set; }
        public string frontCamera { get; set; }
        public string frontCameraResolution { get; set; }
        public string operatingSystem { get; set; }
        public string cpu { get; set; }
        public string ram { get; set; }
        public string internalStorage { get; set; }
        public string mobileNetwork { get; set; }
        public string sim { get; set; }
        public string wifi { get; set; }
        public string gps { get; set; }
        public string bluetooth { get; set; }
        public string chargingPort { get; set; }
        public string headphoneJack { get; set; }
        public string otherConnections { get; set; }
        public string batteryCapacity { get; set; }
        public string batteryTechnology { get; set; }
        public string advancedSecurity { get; set; }
        public string specialFeatures { get; set; }
        public string waterResistance { get; set; }
        public string recording { get; set; }
        public string radio { get; set; }
        public string movieFormats { get; set; }
        public string musicFormats { get; set; }
        public Nullable<int> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
